### ISSUE TITLE
Uncaught exception on page: https://blog.ixk.me/post/my-2022-year-end-summary

### ISSUE THREAD

**Issue by Huazeu** [syfxlin/gatsby-theme-coline#1]
- **URL**: https://blog.ixk.me/post/my-2022-year-end-summary
- **UA**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69

```javascriptLoading chunk 4880 failed.
(error: https://blog.ixk.me/0099e3c0-8dfe2910cb7d47d47179.js)
ChunkLoadError: Loading chunk 4880 failed.
(error: https://blog.ixk.me/0099e3c0-8dfe2910cb7d47d47179.js)
    at p.f.j (https://blog.ixk.me/webpack-runtime-75ab7d3a7d99750e0764.js:1:27600)
    at https://blog.ixk.me/webpack-runtime-75ab7d3a7d99750e0764.js:1:1416
    at Array.reduce (<anonymous>)
    at p.e (https://blog.ixk.me/webpack-runtime-75ab7d3a7d99750e0764.js:1:1381)
    at B.ssr [as requireAsync] (https://blog.ixk.me/66668e0039e3c362409e803df9954a8fd6f89c81-e6144a8cdc148b8df793.js:1:9099)
    at j (https://blog.ixk.me/cb5976b73b0cd7118f18e828ff2da84de23f6a41-bf80c5d18f32e01f66ff.js:2:1195)
    at r.resolveAsync (https://blog.ixk.me/cb5976b73b0cd7118f18e828ff2da84de23f6a41-bf80c5d18f32e01f66ff.js:2:3430)
    at r.loadAsync (https://blog.ixk.me/cb5976b73b0cd7118f18e828ff2da84de23f6a41-bf80c5d18f32e01f66ff.js:2:3089)
    at r.componentDidMount (https://blog.ixk.me/cb5976b73b0cd7118f18e828ff2da84de23f6a41-bf80c5d18f32e01f66ff.js:2:2206)
    at xs (https://blog.ixk.me/app-8be47482295fb88f513f.js:2:217980)
```

**Comment by syfxlin** [comment]
Hi @Huazeu, my blog was migrated from Gatsby.js to Next.js and the residual cache causes page errors, this is a known issue and is usually solved by clearing the cache, please use F5 to refresh the page or clear the site cache and then visit it.
